### ISSUE TITLE
Change Upload to Test S3 upload, not to my actual AWS

### ISSUE THREAD

**Issue by gordonkoehn** [cbg-ethz/sr2silo#72]

**Comment by gordonkoehn** [comment]
```Attaching to sr2silo_sr2silo_1
sr2silo_1  | Traceback (most recent call last):
sr2silo_1  |   File "/app/scripts/vp_transformer.py", line 19, in <module>
sr2silo_1  |     from sr2silo.s3 import compress_bz2, upload_file_to_s3
sr2silo_1  |   File "/app/src/sr2silo/s3.py", line 13, in <module>
sr2silo_1  |     from moto import mock_aws
sr2silo_1  | ModuleNotFoundError: No module named 'moto'
sr2silo_sr2silo_1 exited with code 1
Removing sr2silo_sr2silo_1 ... 
Removing sr2silo_sr2silo_1 ... done
Removing network sr2silo_default
```

This is in docker test. 

It should fail but it does not.

Once it properly fails add moto. 

Probably moto is not found as it is installed as a dev dependency.

**Comment by gordonkoehn** [comment]
Solved in 
- #73
